project                  = "cwb05-dev-dd4e"
project_prefix           = "cwb05"
region                   = ""
environment              = "dev"
user_management_base_url = "https://api-dev.cwb05.dsgov.demo.nuvalence.io/um"
