project                  = "cwb05-dev"
project_prefix           = "cwb05"
region                   = "DEFAULT_REGION"
environment              = "dev"
user_management_base_url = "https://api-dev.cwb05.dsgov.demo.nuvalence.io/um"
